name: Publish to npm

on:
  push:
    tags:
      - "v*"   # triggers only on version tags (e.g. v1.2.3)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Check version consistency
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Package.json version: $PKG_VERSION"
          echo "Git tag version: $TAG_VERSION"
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "❌ Version mismatch!"
            exit 1
          fi
          echo "✅ Versions match"

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🚀 Version ${{ github.ref_name }} published to npm.

            ## Installation
            ```bash
            npx dashboard-studio add <category>/<dashboard-name>
            ```

            ## Changes
            - Describe what’s new here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
